Fix: File Browser roles check boxes are now synchronized with stored …
DNN-Connect/CKEditorProvider pull request #93
Opened 2018-09-27 03:45 UTC by mean2me

…settings

2018-09-30 16:04 UTC, tpluscode commented on CKEditorOptions.ascx.cs
> +                BindOptionsData();
@mean2me I think you did the same change before, moving these two calls. Didn't this change cause issues before?

2018-10-08 12:36 UTC, tpluscode requested changes

2018-10-08 12:36 UTC, tpluscode commented on CKEditorOptions.ascx.cs
> +            return activeRoles;
Actually I would actually change this method to be implemented as generator

```diff
-private List<int> GetActiveRolesIds()
+private IEnumerable<int> GetActiveRolesIds()
// ...
-activeRoles.Add(int.Parse(roleId.Trim()));
+yield return int.Parse(roleId.Trim());
// ...
-return activeRoles;
```

2018-10-17 03:00 UTC, mean2me commented on CKEditorOptions.ascx.cs
> +                BindOptionsData();
@tpluscode I couldn't see any impact after recent changes in CKEditor.

2018-10-23 14:30 UTC, tpluscode approved these changes
Can anyone from @dnnsoftware/tag merge this?

2018-10-23 14:43 UTC, ohine approved these changes

2018-10-23 14:43 UTC, merged