Removed dead "Spell Checker" button from CK Editor toolbar.
DNN-Connect/CKEditorProvider pull request #96
Opened 2018-10-28 03:28 UTC by mean2me

This button is not actually bound to any Spell Checker library. The only usable spell checker we have is SCAYT.

2018-10-28 03:39 UTC, mitchelsellers approved these changes
Looks good to me

2018-10-28 19:11 UTC, daguiler approved these changes

2018-10-29 09:58 UTC, tpluscode commented
Please merge @ohine @zyhfish

2018-10-30 11:03 UTC, zyhfish commented
this is for new installation, how about upgrade scenario which already have default xml files generated.

2018-10-30 12:54 UTC, daguiler commented
> this is for new installation, how about upgrade scenario which already have default xml files generated.

That's a valid point. We could add code here to remove this button:

https://github.com/DNN-Connect/CKEditorProvider/blob/15c572924d999ccbde96bf06181d093af0ef1f9c/Utilities/ToolbarUtil.cs#L51

2018-10-30 12:56 UTC, daguiler requested changes
Reverting approval based on Ben's comment.

2018-10-30 13:08 UTC, mitchelsellers commented
I do not believe we would want to remove it from existing items.  As if we hard-code a removal, then if a user added third-party support for this we could end up breaking it.  (As users can add plugins to CK if they desire.)

2018-10-30 14:53 UTC, daguiler commented
That's right @mitchelsellers. We can leave the PR as is then. Upgrading customers can remove this button manually if they want to by uploading an updated `Dnn.CKToolbarButtons.xml` file via the Assets menu.

2018-10-30 15:09 UTC, mitchelsellers commented
@daguiler I added the Noteworthy tag to this as well so we can remember to mention it in the release notes

2018-10-30 15:38 UTC, daguiler approved these changes

2018-10-31 00:46 UTC, merged