DNN-24450: CKEditor settings error after installation
DNN-Connect/CKEditorProvider pull request #97
Opened 2018-11-07 09:50 UTC by mean2me

Fixed NullReference exception when loading CKEditor settings right after installation

2018-11-07 13:51 UTC, bdukes requested changes

2018-11-07 13:51 UTC, bdukes commented on CKEditorOptions.ascx.cs
> -            lblSelToolb = (Label)UploadFileLimits.HeaderRow.FindControl("SizeLimitLabel");
if these are removed, the next two lines need to be removed as well, right?  otherwise the toolbars get the wrong label.

2018-11-16 09:26 UTC, tpluscode commented on CKEditorOptions.ascx.cs
> -            lblSelToolb = (Label)UploadFileLimits.HeaderRow.FindControl("SizeLimitLabel");
@mean2me please address Brian's comment

2018-11-21 16:31 UTC, daguiler commented
@mean2me, can you fix merge conflicts pls?

2018-11-30 13:26 UTC, daguiler commented
Thanks @mean2me. I think we're good here @bdukes?

2018-11-30 17:11 UTC, bdukes approved these changes

2018-11-30 17:12 UTC, bdukes commented
Looks good to me, except it appears we have merge conflicts again @mean2me

2018-12-01 03:59 UTC, mean2me commented
> Looks good to me, except it appears we have merge conflicts again @mean2me

Hi @bdukes , I tried to merge this branch with development locally and I couldn't see conflicts. Am I missing anything?

2018-12-01 20:12 UTC, merged